version: "3"

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - postgres13:/var/lib/postgresql/data
  redis:
    image: redis:7.0.15-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/store_development
      - REDIS_URL=redis://redis:6379/0
  web:
    build: .
    depends_on:
      db:
        condition: service_started
      sidekiq:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/store_development
      - REDIS_URL=redis://redis:6379/0
    ports:
      - 3000:3000
  test:
    build: .
    command: bash -c "bin/rails db:prepare && bundle exec rspec"
    volumes:
      - .:/rails
    depends_on:
      db:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/store_test
      - RAILS_ENV=test
volumes:
  postgres13:
  redis_data:
